language: java

services:
  - xvfb

jdk:
  - openjdk8

os:
  - linux

#before_install:
#  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
#  - tar xzvf apache-maven-3.6.3-bin.tar.gz
#  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
#  - mvn -v

# override default to do nothing
install: true

before_script:
  - "export DISPLAY=:99.0"

script:
  - export MVN_PARAMS="--batch-mode --update-snapshots -fae -Dmaven.repo.local=xpect-local-maven-repository"
  - mvn -P!tests -Dtarget-platform=eclipse_4_4_2-xtext_2_9_2 $MVN_PARAMS clean install
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_4_2-xtext_2_9_2 $MVN_PARAMS clean integration-test
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_5_0-xtext_2_14_0 $MVN_PARAMS clean integration-test
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_10_0-xtext_nightly $MVN_PARAMS clean integration-test