language: java

jdk:
  - openjdk8

os:
  - linux

# override default to do nothing
install: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - export MVN_PARAMS="--batch-mode --update-snapshots -fae -Dmaven.repo.local=xpect-local-maven-repository"
  - mvn -P!tests -Dtarget-platform=eclipse_4_4_2-xtext_2_9_2 $MVN_PARAMS clean install
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_4_2-xtext_2_9_2 $MVN_PARAMS clean integration-test
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_5_0-xtext_2_14_0 $MVN_PARAMS clean integration-test
  - mvn -P!plugins -P!xtext-examples -Dtarget-platform=eclipse_4_10_0-xtext_nightly $MVN_PARAMS clean integration-test